var express = require('express');
var morgan = require('morgan');
var path = require('path');

var app = express();
app.use(morgan('combined'));

var contentIntro - {
    title: 'ORACLE MIDDLEWARE BLOG',
    heading:'Dealing with Stuck Threads',
    date: 'June 10, 2014',
    body: `<p>
        Most WebLogic administrators have to deal with the Stuck Threads problem from time to time. Stuck threads are JVM threads that have been running for more than a certain configurable time (default 600 seconds).
    </p>
    </p>
    These threads cannot be killed or cleared, but there are still things that an admin can do to alleviate the impact of such undesirable behavior. And the final solution should be finding the root cause of the stuck threads in order to avoid them completely, rather than react when this condition appears. But analysis can be tedious and can take a long time, especially when waiting for an application provider to fix their code.
    </p>
    </p>
    In the meantime, the admin can and should automate the tasks of collecting diagnostic data and recovering from a complete server hang eventually caused by an increasing number of Stuck Threads.
    >/p>
    <p>
    First thing to check when there are Stuck Threads, is to generate a Thread Dump and analyze the threads that are being stuck. It could be that the stuck threads are generated by a problem in the code, by the unavailability of an external system, or it can even be an expected behavior, in the case of some long lasting operations in the application.
    </p>`,
    footer: 'email the review to lenin.basheer@gmail.com'
};

function createMasterTemplate(data){

var  title = data.title;
var date=data.date;
var heading = data.heading;
var body = data.body;
var footer=data.footer;

var contentTemplate=`}
<html>
<head>
    <link href="/ui/style.css" rel="stylesheet"/>
	<title> Personal Page </title>

</head>
<body>
	
	<div class="center">
		<img src="/ui/madi.png" class="icon-small"/>
	</div>
	
	<div>
	 <a href="/">Home</a>
	</div>
	<br>
	<div>
		<h3> ${title} </h3>
		<h4> ${date} </h4>
		<li class="bullets">${heading}</li>
	</div>
	<div>
    	${body}
	</div>
	<div class="right">
    	${footer}
	</div>
	
</body>
</html>
`;
}

app.get('/', function (req, res) {
  res.sendFile(path.join(__dirname, 'ui', 'index.html'));
});

app.get('/ui/style.css', function (req, res) {
  res.sendFile(path.join(__dirname, 'ui', 'style.css'));
});

app.get('/ui/madi.png', function (req, res) {
  res.sendFile(path.join(__dirname, 'ui', 'madi.png'));
});


app.get('/personal', function (req, res) {
  res.sendFile(path.join(__dirname, 'ui', 'intro.html'));
});

app.get('/intro', function (req, res) {
  res.send(createMasterTemplate(contentIntro));
});
app.get('/workbook', function (req, res) {
    res.sendFile(path.join(__dirname, 'ui', 'work.html'));
});


var port = 8080; // Use 8080 for local development because you might already have apache running on 80
app.listen(8080, function () {
  console.log(`IMAD course app listening on port ${port}!`);
});
